import SideMenu from "./_components/Students/StudentSideMenu";
import Context from "./context";

export const metadata = {
  title: "Academiq",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <Context>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </Context>

  );
}
