import SideMenu from "./_components/Students/SideMenu";

export const metadata = {
  title: "Academiq",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
