import SideMenu from "./_components/Students/StudentSideMenu";
import Context from "./context";
import '../app/_styles/globals.css';

export const metadata = {
  title: "Academiq",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <Context>
      <html lang="en">
        <head>
          <link rel="icon" href="/Logo 2.svg" />
        </head>
        <body>
          {children}
        </body>
      </html>
    </Context>

  );
}
